4.-MVC/04-07-2023/MVCEF3Capas/Presentacion/Controllers/AlumnoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Entidades;
using Negocio;

//Es importante hacer referencia de EntityFramework y entityFrameworkSqlServer para que todo funcione
namespace Presentacion.Controllers
{
    public class AlumnoController : Controller
    {
        NAlumno _oAlumno = new NAlumno();
        NEstado _oEstado = new NEstado();
        NEstatus _oEstatus = new NEstatus();
        // GET: Alumno
        public ActionResult Index()
        {
            return View(_oAlumno.Consultar());
        }

        // GET: Alumno/Details/5
        public ActionResult Details(int id)
        {
            return View(_oAlumno.Consultar(id));
        }

        // GET: Alumno/Create
        public ActionResult Create()
        {
            ViewBag.Estados = _oEstado.Consultar();
            ViewBag.Estatus = _oEstatus.Consultar();
            return View();
        }

        // POST: Alumno/Create
        [HttpPost]
        public ActionResult Create(Alumnos alm)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _oAlumno.Agregar(alm);
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.Estados = _oEstado.Consultar();
                    ViewBag.Estatus = _oEstatus.Consultar();
                    return View("Create", alm);
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, "Ocurrió un error al guardar el alumno: " + ex.Message);
                ViewBag.Estados = _oEstado.Consultar();
                ViewBag.Estatus = _oEstatus.Consultar();
                return View();
            }
        }

        // GET: Alumno/Edit/5
        public ActionResult Edit(int id)
        {
            ViewBag.Estados = _oEstado.Consultar();
            ViewBag.Estatus = _oEstatus.Consultar();
            return View(_oAlumno.Consultar(id));
        }

        // POST: Alumno/Edit/5
        [HttpPost]
        public ActionResult Edit(Alumnos alm)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _oAlumno.Actualizar(alm);
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.Estados = _oEstado.Consultar();
                    ViewBag.Estatus = _oEstatus.Consultar();
                    return View("Edit", alm);
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, "Ocurrió un error al guardar el alumno: " + ex.Message);
                ViewBag.Estados = _oEstado.Consultar();
                ViewBag.Estatus = _oEstatus.Consultar();
                return View();
            }
        }

        // GET: Alumno/Delete/5
        public ActionResult Delete(int id)
        {
            return View(_oAlumno.Consultar(id));
        }

        // POST: Alumno/Delete/5
        [HttpPost]
        public ActionResult Delete(Alumnos alm)
        {
            try
            {
                _oAlumno.Eliminar(alm.id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        Negocio.srWCFAlumno.WCFAlumnosClient wCFAlumnos = new Negocio.srWCFAlumno.WCFAlumnosClient();
        public ActionResult _AportacionesIMSS(int id)
        {
            
            Negocio.srWCFAlumno.AportacionesIMSS imss =  wCFAlumnos.CalcularIMSS(id);
            return PartialView(imss);
        }

        public ActionResult _TablaISR(int id)
        {
            Negocio.srWCFAlumno.ItemTablaISR isr = wCFAlumnos.CalcularISR(id);
            return PartialView(isr);
        }
    }
}

4.-MVC/04-07-2023/MVCEF3Capas/Presentacion/Controllers/EstatusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Entidades;
using Negocio;

namespace Presentacion.Controllers
{
    public class EstatusController : Controller
    {
        NEstatusAlumnos _estatus = new NEstatusAlumnos();
        // GET: Estatus
        public ActionResult Index()
        {
            return View(_estatus.Consultar());
        }

        // GET: Estatus/Details/5
        public ActionResult Details(int id)
        {
            return View(_estatus.Consultar(id));
        }

        // GET: Estatus/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Estatus/Create
        [HttpPost]
        public ActionResult Create(EstatusAlumnos est)
        {
            try
            {
                _estatus.Agregar(est);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Estatus/Edit/5
        public ActionResult Edit(int id)
        {
            return View(_estatus.Consultar(id));
        }

        // POST: Estatus/Edit/5
        [HttpPost]
        public ActionResult Edit(EstatusAlumnos est)
        {
            try
            {
                _estatus.Actualizar(est);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Estatus/Delete/5
        public ActionResult Delete(int id)
        {
            return View(_estatus.Consultar(id));
        }

        // POST: Estatus/Delete/5
        [HttpPost]
        public ActionResult Delete(EstatusAlumnos est)
        {
            try
            {
                _estatus.Eliminar(est.id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

4.-MVC/04-07-2023/MVCEF3Capas/Presentacion/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Presentacion.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

4.-MVC/04-07-2023/MVCEF3Capas/Presentacion/Views/Alumno/Create.cshtml
@model Entidades.Alumnos

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Agregar un Alumno</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="row mb-3">
            <div class="col-sm-2 d-flex justify-content-end"><strong>@Html.LabelFor(model => model.nombre, htmlAttributes: new {@id ="nom"})</strong></div>
            <div class="col-sm-3">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control", @id = "nom" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-sm-2 d-flex justify-content-end"><strong><label for="ap">Primer Apellido</label></strong></div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.primerApellido, new { htmlAttributes = new { @class = "form-control", @id = "ap" } })
                @Html.ValidationMessageFor(model => model.primerApellido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-sm-2 d-flex justify-content-end"><strong><label for="am">Segundo Apellido</label></strong></div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.segundoaPellido, new { htmlAttributes = new { @class = "form-control", @id = "am" } })
                @Html.ValidationMessageFor(model => model.segundoaPellido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-sm-2 d-flex justify-content-end"><strong><label for="cor">Correo</label></strong></div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.correo, new { htmlAttributes = new { @class = "form-control", @id = "cor" } })
                @Html.ValidationMessageFor(model => model.correo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-sm-2 d-flex justify-content-end"><strong><label for="tel">Telefono</label></strong></div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.telefono, new { htmlAttributes = new { @class = "form-control", @id = "tel", @maxlength = 10, type = "number", inputmode = "numeric" } })
                @Html.ValidationMessageFor(model => model.telefono, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-sm-2 d-flex justify-content-end"><strong><label for="fn">Fecha de Nacimiento</label></strong></div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.fechaNacimiento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fechaNacimiento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-sm-2 d-flex justify-content-end"><strong><label for="curp">CURP</label></strong></div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.curp, new { htmlAttributes = new { @class = "form-control", @id = "curp", @maxlength = 18 } })
                @Html.ValidationMessageFor(model => model.curp, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-sm-2 d-flex justify-content-end"><strong><label for="sueldo">Sueldo</label></strong></div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.sueldo, new { htmlAttributes = new { @class = "form-control", @id = "sueldo", type = "number", inputmode = "numeric" } })
                @Html.ValidationMessageFor(model => model.sueldo, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-sm-2 d-flex justify-content-end"><strong><label for="est">Estado</label></strong></div>
            <div class="col-md-10">
                @Html.DropDownList("idEstadoOrigen", new SelectList(ViewBag.Estados, "id", "nombre"), htmlAttributes: new { @class = "form-control", @id = "est" })
                @Html.ValidationMessageFor(model => model.idEstadoOrigen, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-sm-2 d-flex justify-content-end"><strong><label for="ea">Estatus</label></strong></div>
            <div class="col-md-10">
                @Html.DropDownList("idEstatus", new SelectList(ViewBag.Estatus, "id", "nombre"), htmlAttributes: new { @class = "form-control", @id = "ea" })
                @Html.ValidationMessageFor(model => model.idEstatus, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="row mb-3">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-light" />
            </div>
        </div>
    </div>
}
<br />
<p>
    @Html.ActionLink("Regresar a la Lista", "Index", null, htmlAttributes: new { @class = "btn btn-link text-decoration-none" })
</p>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

4.-MVC/04-07-2023/MVCEF3Capas/Presentacion/Views/Alumno/Delete.cshtml
@model Entidades.Alumnos
@using System.Globalization
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Eliminar Alumno</h2>
<h3 class="text-danger">¿Esta seguro que desea eliminar al Alumno?</h3>

<div>
    <hr />
    <dl class="dl-horizontal">
        <div class="row">
            <div class="col-sm-2 d-flex justify-content-end">
                <dt>
                    ID
                </dt>
            </div>
            <div class="col-sm-3">
                <dd>
                    @Html.DisplayFor(model => model.id)
                </dd>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-2 d-flex justify-content-end">
                <dt>
                    Nombre
                </dt>
            </div>
            <div class="col-sm-3">
                <dd>
                    @Html.DisplayFor(model => model.nombre)
                </dd>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-2 d-flex justify-content-end">
                <dt>
                    Primer Apellido
                </dt>
            </div>
            <div class="col-sm-3">
                <dd>
                    @Html.DisplayFor(model => model.primerApellido)
                </dd>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-2 d-flex justify-content-end">
                <dt>
                    Segundo Apellido
                </dt>
            </div>
            <div class="col-sm-3">
                <dd>
                    @Html.DisplayFor(model => model.segundoaPellido)
                </dd>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-2 d-flex justify-content-end">
                <dt>
                    Correo
                </dt>
            </div>
            <div class="col-sm-3">
                <dd>
                    <a href="mailto:@Model.correo" class="correo-enlace">@Model.correo</a>
                </dd>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-2 d-flex justify-content-end">
                <dt>
                    Telefono
                </dt>
            </div>
            <div class="col-sm-3">
                <dd>
                    @Html.DisplayFor(model => model.telefono)
                </dd>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-2 d-flex justify-content-end">
                <dt>
                    Fecha de Nacimiento
                </dt>
            </div>
            <div class="col-sm-3">
                <dd>
                    @Model.fechaNacimiento.ToString("yyyy-MM-dd")
                </dd>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-2 d-flex justify-content-end">
                <dt>
                    CURP
                </dt>
            </div>
            <div class="col-sm-3">
                <dd>
                    @Html.DisplayFor(model => model.curp)
                </dd>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-2 d-flex justify-content-end">
                <dt>
                    Sueldo
                </dt>
            </div>
            <div class="col-sm-3">
                <dd>
                    @{
                        var formattedSueldo = string.Format("{0:C}", Model.sueldo);
                    }
                    @Html.DisplayFor(model => formattedSueldo)
                </dd>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-2 d-flex justify-content-end">
                <dt>
                    Estado
                </dt>
            </div>
            <div class="col-sm-3">
                <dd>
                    @Html.DisplayFor(model => model.Estados.nombre)
                </dd>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-2 d-flex justify-content-end">
                <dt>
                    Estatus
                </dt>
            </div>
            <div class="col-sm-3">
                <dd>
                    @Html.DisplayFor(model => model.EstatusAlumnos.nombre)
                </dd>
            </div>
        </div>

        <button id="btnEliminar" class="btn btn-light" onclick="mostrarModalConfirmacion()">Eliminar</button>
</div>
<p>
    @Html.ActionLink("Regresar a la Lista", "Index", null, htmlAttributes: new { @class = "btn btn-link text-decoration-none" })
</p>
<div id="confirmarEliminarModal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Confirmar Eliminación</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>¿Está seguro que desea eliminar al alumno?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                        <input type="submit" value="Eliminar" class="btn btn-danger" />
                }
            </div>
        </div>
    </div>
</div>
<style>
    .correo-enlace {
        color: black;
        text-decoration: none;
    }
</style>
<script>
    function mostrarModalConfirmacion() {
        var modal = document.getElementById('confirmarEliminarModal');
        var modalInstance = new bootstrap.Modal(modal);
        modalInstance.show();
    }
</script>

4.-MVC/04-07-2023/MVCEF3Capas/Presentacion/Views/Alumno/Details.cshtml
@model Entidades.Alumnos
@using System.Globalization

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detalles del Alumno</h2>

<div>
    <hr />
    <div class="row">
        <div class="col-sm-2 d-flex justify-content-end">
            ID
        </div>
        <div class="col-sm-3">
            @Html.DisplayFor(model => model.id)
        </div>
    </div>
    <div class="row">
        <div class="col-sm-2 d-flex justify-content-end">
            Nombre
        </div>
        <div class="col-sm-3">
            @Html.DisplayFor(model => model.nombre)
        </div>
    </div>
    <div class="row">
        <div class="col-sm-2 d-flex justify-content-end">
            Primer Apellido
        </div>
        <div class="col-sm-3">
            @Html.DisplayFor(model => model.primerApellido)
        </div>
    </div>
    <div class="row">
        <div class="col-sm-2 d-flex justify-content-end">
            Segundo Apellido
        </div>
        <div class="col-sm-3">
            @Html.DisplayFor(model => model.segundoaPellido)
        </div>
    </div>
    <div class="row">
        <div class="col-sm-2 d-flex justify-content-end">
            Correo
        </div>
        <div class="col-sm-3">
            <a href="mailto:@Model.correo" class="correo-enlace">@Model.correo</a>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-2 d-flex justify-content-end">
            Telefono
        </div>
        <div class="col-sm-3">
            @Html.DisplayFor(model => model.telefono)
        </div>
    </div>
    <div class="row">
        <div class="col-sm-2 d-flex justify-content-end">
            Fecha de Nacimiento
        </div>
        <div class="col-sm-3">
            @Model.fechaNacimiento.ToString("yyyy-MM-dd")
        </div>
    </div>
    <div class="row">
        <div class="col-sm-2 d-flex justify-content-end">
            CURP
        </div>
        <div class="col-sm-3">
            @Html.DisplayFor(model => model.curp)
        </div>
    </div>
    <div class="row">
        <div class="col-sm-2 d-flex justify-content-end">
            Sueldo
        </div>
        <div class="col-sm-3">
            @{
                var formattedSueldo = string.Format("{0:C}", Model.sueldo);
            }
            @Html.DisplayFor(model => formattedSueldo)
        </div>
    </div>
    <div class="row">
        <div class="col-sm-2 d-flex justify-content-end">
            Estado
        </div>
        <div class="col-sm-3">
            @Html.DisplayFor(model => model.Estados.nombre)
        </div>
    </div>
    <div class="row">
        <div class="col-sm-2 d-flex justify-content-end">
            Estatus
        </div>
        <div class="col-sm-3">
            @Html.DisplayFor(model => model.EstatusAlumnos.nombre)
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-sm-2 d-flex justify-content-center">
            <button type="button" class="btn btn-primary" onclick="IMSS()">Calcular IMSS</button>
        </div>
        <div class="col-sm-3">
            <button type="button" class="btn btn-light" onclick="ISR()">Calcular ISR</button>
        </div>
    </div>
</div>
<p>
    @Html.ActionLink("Regresar a la Lista", "Index", null, htmlAttributes: new { @class = "btn btn-link text-decoration-none" })
</p>

<style>
    .correo-enlace {
        color: black;
        text-decoration: none;
    }
</style>

<div class="modal fade" id="modal" tabindex="-1" aria-labelledby="modallabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="modallabel"></h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="contenidoModal">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    function IMSS() {
        var id = @Html.DisplayFor(model => model.id);
        $("#modallabel").text("Calculo del IMSS");
        var url = "@Url.Action("_AportacionesIMSS", "Alumno")" + "/" + id;
        ajaxGethtml(url, funcExito);
    }

    function ISR() {
        var id = @Html.DisplayFor(model => model.id);
        $("#modallabel").text("Calculo del ISR");
        var url = "@Url.Action("_TablaISR", "Alumno")" + "/" + id;
        ajaxGethtml(url, funcExito);
    }

    function funcExito(data) {
        $("#contenidoModal").html(data);
        $("#modal").modal("show");
    }
</script>

@Scripts.Render("~/bundles/tichajax")

4.-MVC/04-07-2023/MVCEF3Capas/Presentacion/Views/Alumno/Edit.cshtml
@model Entidades.Alumnos

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>Actualizar Alumno</h2>

@using (Html.BeginForm())
{
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="row mb-3">
            <div class="col-sm-2 d-flex justify-content-end"><strong><label for="id">ID</label></strong></div>
            
            <div class="col-md-10">
                @Html.EditorFor(model => model.id, new { htmlAttributes = new { @class = "form-control", @disabled = "true" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-sm-2 d-flex justify-content-end"><strong><label for="nom">Nombre</label></strong></div>
            
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control", @id = "nom" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-sm-2 d-flex justify-content-end"><strong><label for="ap">Primer Apellido</label></strong></div>
            
            <div class="col-md-10">
                @Html.EditorFor(model => model.primerApellido, new { htmlAttributes = new { @class = "form-control", @id = "ap" } })
                @Html.ValidationMessageFor(model => model.primerApellido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-sm-2 d-flex justify-content-end"><strong><label for="am">Segundo Apellido</label></strong></div>
            
            <div class="col-md-10">
                @Html.EditorFor(model => model.segundoaPellido, new { htmlAttributes = new { @class = "form-control", @id = "am" } })
                @Html.ValidationMessageFor(model => model.segundoaPellido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-sm-2 d-flex justify-content-end"><strong><label for="cor">Correo</label></strong></div>
            
            <div class="col-md-10">
                @Html.EditorFor(model => model.correo, new { htmlAttributes = new { @class = "form-control", @id = "cor" } })
                @Html.ValidationMessageFor(model => model.correo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-sm-2 d-flex justify-content-end"><strong><label for="tel">Telefono</label></strong></div>
            
            <div class="col-md-10">
                @Html.EditorFor(model => model.telefono, new { htmlAttributes = new { @class = "form-control", @id = "tel", @maxlength = 10, type = "number", inputmode = "numeric" } })
                @Html.ValidationMessageFor(model => model.telefono, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-sm-2 d-flex justify-content-end"><strong><label for="fn">Fecha de Nacimiento</label></strong></div>
            
            <div class="col-md-10">
                @Html.EditorFor(model => model.fechaNacimiento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fechaNacimiento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-sm-2 d-flex justify-content-end"><strong><label for="curp">CURP</label></strong></div>
            
            <div class="col-md-10">
                @Html.EditorFor(model => model.curp, new { htmlAttributes = new { @class = "form-control", @id = "curp", @maxlength = 18 } })
                @Html.ValidationMessageFor(model => model.curp, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-sm-2 d-flex justify-content-end"><strong><label for="sueldo">Sueldo</label></strong></div>
            
            <div class="col-md-10">
                @Html.EditorFor(model => model.sueldo, new { htmlAttributes = new { @class = "form-control", @id = "sueldo", type = "number", inputmode = "numeric" } })
                @Html.ValidationMessageFor(model => model.sueldo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-sm-2 d-flex justify-content-end"><strong><label for="est">Estado</label></strong></div>
            
            <div class="col-md-10">
                @Html.DropDownList("idEstadoOrigen", new SelectList(ViewBag.Estados, "id", "nombre"), htmlAttributes: new { @class = "form-control", @id = "est" })
                @Html.ValidationMessageFor(model => model.idEstadoOrigen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-sm-2 d-flex justify-content-end"><strong><label for="ea">Estatus</label></strong></div>
            
            <div class="col-md-10">
                @Html.DropDownList("idEstatus", new SelectList(ViewBag.Estatus, "id", "nombre"), htmlAttributes: new { @class = "form-control", @id = "ea" })
                @Html.ValidationMessageFor(model => model.idEstatus, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="row mb-3">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-light" />
            </div>
        </div>
    </div>
}
<br />
<p>
    @Html.ActionLink("Regresar a la Lista", "Index", null, htmlAttributes: new { @class = "btn btn-link text-decoration-none" })
</p>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

4.-MVC/04-07-2023/MVCEF3Capas/Presentacion/Views/Alumno/_AportacionesIMSS.cshtml
@model Negocio.srWCFAlumno.AportacionesIMSS

<div>
    <dl class="dl-horizontal">
        <dt>
            <label>Cesantia</label>
        </dt>

        <dd>
            @Model.Cesantia.ToString("C")
        </dd>

        <dt>
            <label>Enfermedades y Maternidad</label>
        </dt>

        <dd>
            @Model.EnfermedadMaternidad.ToString("C")
        </dd>

        <dt>
            <label>Infonavit</label>
        </dt>

        <dd>
            @Model.Infonavit.ToString("C")
        </dd>

        <dt>
            <label>Invalidez y Vida</label>
        </dt>

        <dd>
            @Model.InvalidezVida.ToString("C")
        </dd>

        <dt>
            <label>Retiro</label>
        </dt>

        <dd>
            @Model.Retiro.ToString("C")
        </dd>

    </dl>
</div>

@Scripts.Render("~/bundles/tichajax")